### PR TITLE
Update github id

### PR DESCRIPTION
**Pull request by kana820**
## What
Changed to my github id in the README.

## CHECKS :warning:

Please make sure you are aware of the following.

- [x] **The changes in this PR doesn't have private information

### CODE REVIEW

**Comment by dxtym** [comment]
Awesome!

**Comment by sanusatyadarshi** [comment]
Looks good :) 

Please ask other team members to also check and verify.

**Comment by aoi0108** [comment]
Great!

**Comment by thisagi** [comment]
That’s great!

**Pull request merged**
